### ISSUE TITLE
when fragment is not defined typeError is thrown

### ISSUE THREAD

**Issue by capaj** [stems/graphql-depth-limit#9]
```
{
  "error": {
    "errors": [
      {
        "message": "Cannot read property 'kind' of undefined",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "TypeError: Cannot read property 'kind' of undefined",
              "    at determineDepth (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:81:16)",
              "    at determineDepth (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:107:14)",
              "    at Math.max.node.selectionSet.selections.map (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:94:13)",
              "    at Array.map (<anonymous>)",
              "    at determineDepth (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:93:43)",
              "    at Math.max.node.selectionSet.selections.map (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:121:11)",
              "    at Array.map (<anonymous>)",
              "    at determineDepth (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:120:41)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/graphql-depth-limit/index.js:21:27",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/graphql/validation/validate.js:51:12",
              "    at Array.map (<anonymous>)",
              "    at Object.validate (/home/capaj/work-repos/looop/project-alpha/node_modules/graphql/validation/validate.js:50:53)",
              "    at validate (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/src/requestPipeline.ts:426:22)",
              "    at Object.<anonymous> (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/src/requestPipeline.ts:250:32)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)",
              "From previous event:",
              "    at __awaiter (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/requestPipeline.js:3:12)",
              "    at Object.processGraphQLRequest (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/requestPipeline.js:40:12)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/src/runHttpQuery.ts:292:32",
              "    at Generator.next (<anonymous>)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:7:71",
              "From previous event:",
              "    at __awaiter (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:3:12)",
              "    at processHTTPRequest (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:96:12)",
              "    at Object.<anonymous> (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/src/runHttpQuery.ts:184:10)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:4:58)",
              "    at runCallback (timers.js:705:18)",
              "    at tryOnImmediate (timers.js:676:5)",
              "    at processImmediate (timers.js:658:5)",
              "    at process.topLevelDomainCallback (domain.js:126:23)",
              "From previous event:",
              "    at Promise.then (/home/capaj/work-repos/looop/project-alpha/node_modules/sequelize/lib/promise.js:21:17)",
              "    at step (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:6:124)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:7:9",
              "    at __awaiter (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:3:12)",
              "    at Object.runHttpQuery (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:40:12)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/expressApollo.ts:35:5",
              "    at app.use (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/ApolloServer.ts:211:9)",
              "    at Layer.handle [as handle_request] (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/layer.js:95:5)",
              "    at trim_prefix (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:317:13)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:284:7",
              "    at Function.process_params (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:335:12)",
              "    at next (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:275:10)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/ApolloServer.ts:69:5",
              "From previous event:",
              "    at __awaiter (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:3:12)",
              "    at Object.runHttpQuery (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-core/dist/runHttpQuery.js:40:12)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/expressApollo.ts:35:5",
              "    at app.use (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/ApolloServer.ts:211:9)",
              "    at Layer.handle [as handle_request] (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/layer.js:95:5)",
              "    at trim_prefix (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:317:13)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:284:7",
              "    at Function.process_params (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:335:12)",
              "    at next (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:275:10)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/ApolloServer.ts:69:5",
              "    at Layer.handle [as handle_request] (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/layer.js:95:5)",
              "    at trim_prefix (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:317:13)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:284:7",
              "    at Function.process_params (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:335:12)",
              "    at next (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:275:10)",
              "    at jsonParser (/home/capaj/work-repos/looop/project-alpha/node_modules/body-parser/lib/types/json.js:101:7)",
              "From previous event:",
              "    at Promise.then (/home/capaj/work-repos/looop/project-alpha/node_modules/sequelize/lib/promise.js:21:17)",
              "    at app.use (/home/capaj/work-repos/looop/project-alpha/node_modules/apollo-server-express/src/ApolloServer.ts:132:24)",
              "    at Layer.handle [as handle_request] (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/layer.js:95:5)",
              "    at trim_prefix (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:317:13)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:284:7",
              "    at Function.process_params (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:335:12)",
              "    at next (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:275:10)",
              "    at app.use (/home/capaj/work-repos/looop/project-alpha/back-end/src/graphql/graphqlMiddlewares.ts:53:5)",
              "    at Layer.handle [as handle_request] (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/layer.js:95:5)",
              "    at trim_prefix (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:317:13)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:284:7",
              "    at Function.process_params (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:335:12)",
              "    at next (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:275:10)",
              "    at default_1 (/home/capaj/work-repos/looop/project-alpha/back-end/src/route/expressTimeoutMiddleware.ts:21:3)",
              "    at Layer.handle [as handle_request] (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/layer.js:95:5)",
              "    at trim_prefix (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:317:13)",
              "    at /home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:284:7",
              "    at Function.process_params (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:335:12)",
              "    at next (/home/capaj/work-repos/looop/project-alpha/node_modules/express/lib/router/index.js:275:10)"
            ]
          }
        }
      }
    ]
  }
}
```

happens when I send a request like this:
```
{
  topic(id: 29) {
    ...topicWithEnrolment
  }
}

fragment TopicWithEnrolment on ITopicModel {
  id
  __typename
}

```
notice the `t` is not capital letter in the query.

**Comment by rylanc** [comment]
Any update on this? I just ran into it myself

**Comment by cesargdm** [comment]
Sill happenning with
```
TypeError: Cannot read property 'kind' of undefined
    at determineDepth (/<PATH>/node_modules/graphql-depth-limit/index.js:60:16)
    at determineDepth (/<PATH>/node_modules/graphql-depth-limit/index.js:72:14)
    at /<PATH>/node_modules/graphql-depth-limit/index.js:69:9
    at Array.map (<anonymous>)
    at determineDepth (/<PATH>/node_modules/graphql-depth-limit/index.js:68:59)
    at /<PATH>/node_modules/graphql-depth-limit/index.js:77:9
    at Array.map (<anonymous>)
    at determineDepth (/<PATH>/node_modules/graphql-depth-limit/index.js:76:55)
    at /<PATH>/node_modules/graphql-depth-limit/index.js:22:27
    at /<PATH>/node_modules/graphql/validation/validate.js:65:12
```

**Comment by cesargdm** [comment]
https://github.com/stems/graphql-depth-limit/pull/10/files
